#include "operations.h"
#include "Progress.h"
#include "Utils.h"
#include "Files.h"
#include "../BNKCore.cpp"
#include "../Audio/XmaDecoder.h"
#include <filesystem>
#include <fstream>
#include <thread>
#include <atomic>
#include <mutex>
#include <vector>
#include <unordered_map>
#include <algorithm>
#include <optional>
#include "../MDL/mdl_converter.h"
#include <cstring>
#include <zlib.h>

#include "operations/Paths/Output.inl"
#include "operations/Extraction/SelectedRaw.inl"
#include "operations/Audio/SelectedWav.inl"
#include "operations/Extraction/DumpAll.inl"
#include "operations/Audio/Export.inl"
#include "operations/Textures/RebuildAll.inl"
#include "operations/Models/RebuildAll.inl"
#include "operations/Textures/RebuildOne.inl"
#include "operations/Models/RebuildOne.inl"
#include "operations/Global/DumpAll.inl"
#include "operations/Global/Audio.inl"
#include "operations/Global/Textures.inl"
#include "operations/Global/Models.inl"
#include "operations/Animation/AdbDecompress.inl"
#include "operations/Animation/Selected.inl"
#include "operations/Animation/All.inl"
#include "operations/Glb/Selected.inl"
#include "operations/Glb/All.inl"
#include "operations/Glb/Global.inl"
