#ifdef _WIN32
#include "EntityDetails/Overlays/GdbPlacements.inl"
#include "EntityDetails/State/Selection.inl"
#include "EntityDetails/Containers/Labels.inl"
#include "EntityDetails/Containers/AuthoredRules.inl"
#include "EntityDetails/Containers/LootEditor.inl"
#include "EntityDetails/Details/EntityGameplay.inl"
#include "EntityDetails/Details/Property.inl"
#include "EntityDetails/Details/ExistingContainer.inl"
#include "EntityDetails/Details/AdditionContainer.inl"
#include "EntityDetails/Containers/SpawnChoices.inl"
#include "EntityDetails/Quest/LevelReference.inl"
#include "EntityDetails/Selection/SpawnMarker.inl"
#include "EntityDetails/Quest/AddItem.inl"
#include "EntityDetails/Overlays/SpawnMarkers.inl"
#endif
