std::string generate_childhood_skip_patch_lua(
    const AuthoredQuest& quest) {
    const AuthoredNode& approach =
        *find_kind(quest, AuthoredNodeKind::ApproachNpc);
    const AuthoredNode& prompt =
        *find_kind(quest, AuthoredNodeKind::HoldInteraction);
    const std::string prompt_tag = node_tag(quest, prompt);
    const std::string title_tag = "Quest_" + quest.quest_id;
    const std::string accept_tag = patch_accept_tag(quest);
    const std::string box_tag = quest.quest_id + "_SkipPrompt";

    std::ostringstream lua;
    lua << "module(..., package.seeall)\n"
        << "QuestManager.NewQuestThread(\"" << quest.quest_id << "\")\n\n"
        << "function " << quest.quest_id << ":Init()\n"
        << "  self.SkipRequested = false\n"
        << "end\n\n"
        << "function " << quest.quest_id << ":Update()\n"
        << "  while Gameflow.Childhood == nil and "
           "Gameflow.PositionInGameflow <= ScriptEnum.DebugQC060 do\n"
        << "    coroutine.yield()\n"
        << "  end\n"
        << "  if Gameflow.Childhood == nil then return end\n"
        << "  while not self.SkipRequested and "
           "Gameflow.Childhood ~= nil and "
           "not Gameflow.Childhood.Terminated do\n"
        << "    coroutine.yield()\n"
        << "  end\n"
        << "  if not self.SkipRequested or Gameflow.Childhood == nil then "
           "return end\n"
        << "  while Gameflow.ChildhoodVars == nil or "
           "Gameflow.ChildhoodVars.SkipToLuciensStudy == nil do\n"
        << "    coroutine.yield()\n"
        << "  end\n"
        << "  local dog = GetDog()\n"
        << "  if dog == nil or not dog:IsAlive() then\n"
        << "    ScriptFunction.CreateDog()\n"
        << "    self:WaitFor(function()\n"
        << "      local created_dog = GetDog()\n"
        << "      return created_dog ~= nil and created_dog:IsAlive()\n"
        << "    end)\n"
        << "  end\n"
        << "  QuestManager.DogEntity = GetDog()\n"
        << "  Gameflow.ChildhoodVars.SkipToLuciensStudy()\n"
        << "  self:WaitFor(function()\n"
        << "    return IsLevelLoaded(\"FairfaxCastleGardens\")\n"
        << "  end)\n"
        << "  local childhood = Gameflow.Childhood\n"
        << "  if childhood == nil or childhood.Terminated then return end\n"
        << "  childhood.DisperseCrowd = true\n"
        << "  childhood.MurgoPitchDone = true\n"
        << "  childhood.Morning = true\n"
        << "  childhood.CarriageBoarded = true\n"
        << "  childhood.GoToCastle = true\n"
        << "  childhood.CircleActive = true\n"
        << "  childhood.EndChildhood = true\n"
        << "end\n\n"
        << "QuestManager.NewEntityThread("
        << lua_quote(approach.entity.entity_name) << ")\n\n"
        << "function " << approach.entity.entity_name << ":Init()\n"
        << "  self.SkipPromptTag = " << lua_quote(box_tag) << "\n"
        << "end\n\n"
        << "function " << approach.entity.entity_name << ":CustomUpdate()\n"
        << (approach.entity.entity_name.rfind("F2AB_Static_", 0) == 0
                ? std::string()
                : "  ScriptFunction.DisableSimBehaviours(self.Entity)\n"
                  "  Navigation.StopMoving(self.Entity)\n"
                  "  PhysicsCharacter.SetAsPushableByHero(self.Entity, "
                  "false)\n"
                  "  Health.SetAsInvulnerable(self.Entity, true)\n"
                  "  OpinionReaction.SetRespondToExpressions(self.Entity, "
                  "false)\n")
        << "  while not self.ParentQuest.SkipRequested do\n"
        << "    if IsDistanceBetweenThingsUnder("
        << "self.Entity, QuestManager.HeroEntity, "
        << approach.approach_radius << ") then\n"
        << "      GUI.DisplayInfoBoxParams({\n"
        << "        Name = self.SkipPromptTag,\n"
        << "        Title = " << lua_quote(title_tag) << ",\n"
        << "        AcceptText = " << lua_quote(accept_tag) << ",\n"
        << "        IsHoldAButton = true,\n"
        << "        ShowYButton = false,\n"
        << "        DisplayBoxStyle = "
           "EDisplayBoxStyle.DBS_QUEST_ACCEPTANCE\n"
        << "      }, " << lua_quote(prompt_tag) << ")\n"
        << "      while IsDistanceBetweenThingsUnder("
        << "self.Entity, QuestManager.HeroEntity, "
        << approach.approach_radius
        << ") and not self.ParentQuest.SkipRequested do\n"
        << "        local is_posted, message = "
           "MessageEvents.IsMessagePosted("
           "EMessageEventType.MESSAGE_EVENT_INFOBOX, "
           "self.LastMessageID_PressedAButton)\n"
        << "        if is_posted then\n"
        << "          self.LastMessageID_PressedAButton = message:GetID()\n"
        << "          if message:GetExtraDataAsNumber() == 1 then\n"
        << "            self.ParentQuest.SkipRequested = true\n"
        << "          end\n"
        << "        end\n"
        << "        coroutine.yield()\n"
        << "      end\n"
        << "      GUI.RemoveDisplayBox(self.SkipPromptTag)\n"
        << "    end\n"
        << "    coroutine.yield()\n"
        << "  end\n"
        << "  GUI.RemoveDisplayBox(self.SkipPromptTag)\n"
        << "end\n";
    return lua.str();
}
